session_name: Dotfiles
windows:
  - window_name: .dotfiles
    start_directory: '~/.dotfiles'
    panes:
      - shell_command:
        - cmd: 'c'
        - cmd: 'vim'
  - window_name: AstroNvim
    start_directory: '~/.config/nvim'
    panes:
      - shell_command:
        - cmd: 'c'
  - window_name: Plugins
    start_directory: '~/.local/share/nvim/lazy'
    panes:
      - shell_command:
        - cmd: 'c'
