session_name: Loop Returns
start_directory: "~/Code/loop-returns-app"
windows:
  - window_name: Project
    panes:
      - shell_command:
        - cmd: 'c'
        - cmd: "vim"
  - window_name: Admin
    panes:
      - shell_command:
        - cmd: 'c'
        - cmd: "vim"
  - window_name: Frontend
    panes:
      - shell_command:
        - cmd: 'c'
        - cmd: "vim"
  - window_name: Terminals
    layout: main-vertical
    panes:
      - pane:
      - pane:
        start_directory: '~/Code/loop-returns-app/admin'
      - pane:
        start_directory: '~/Code/loop-returns-app/frontend/'

