session_name: Loop Returns
start_directory: "~/Code/loop-returns-app"
windows:
  - window_name: Root
    panes:
      - shell_command:
        - cmd: 'c'
        - cmd: "vim"
  - window_name: Admin
    start_directory: ./admin
    panes:
      - shell_command:
        - cmd: 'c'
        - cmd: "vim"
  - window_name: Frontend
    start_directory: ./frontend
    panes:
      - shell_command:
        - cmd: 'c'
        - cmd: "vim"
  - window_name: Terminals
    layout: main-vertical
    focus: true
    panes:
      - pane:
        focus: true
      - shell_command:
        - cd admin
        - clear
      - shell_command:
        - cmd: 'cd frontend'
        - cmd: 'clear'

