session_name: Notes
windows:
  - window_name: Loop
    start_directory: "~/Documents/Loop"
    panes:
      - shell_command:
        - cmd: 'c'
        - cmd: "vim"
  - window_name: GRIN
    start_directory: "~/Documents/GRIN-Vault/"
    panes:
      - shell_command:
        - cmd: 'c'
        - cmd: "vim"
