session_name: QMK Firmware
start_directory: ~/Code/qmk_firmware
windows:
  - window_name: Userland
    start_directory: ./users/adaviloper
    panes:
      - shell_command:
        - cmd: 'c'
  - window_name: Lily58
    start_directory: ./keyboards/lily58/keymaps/adaviloper
    panes:
      - shell_command:
        - cmd: 'c'
  - window_name: Lulu
    start_directory: ./keyboards/boardsource/lulu/keymaps/adaviloper
    panes:
      - shell_command:
        - cmd: 'c'
  - window_name: Unicorne
    start_directory: ./keyboards/boardsource/unicorne/keymaps/default
    panes:
      - shell_command:
        - cmd: 'c'
  - window_name: DZ60
    start_directory: ./keyboards/dz60/keymaps/adaviloper
    panes:
      - shell_command:
        - cmd: 'c'
  - window_name: Root
    panes:
      - shell_command:
        - cmd: 'c'
