code_transform.class_new.variants:
    Jobs: laravel_job
    Listeners: laravel_listener
    Models: laravel_model
    Feature: phpunit_feature
    Unit: phpunit_unit
phpunit.enabled: true
language_server_worse_reflection.inlay_hints.enable: true
