# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '''
[┌───────────────────>](bold green)
[│](bold green) $username$directory$git_branch$git_state$git_status$git_metrics
[└─>](bold green) '''

right_format = '$time'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[directory]
fish_style_pwd_dir_length = 3
truncation_length = 3
truncation_symbol = '.../'

[directory.substitutions]
# Add any substitions here
# 'some/path' = 'alias'

[git_status]
disabled = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[time]
disabled = false
format = '[$time]($style) '

[username]
format = '[adaviloper]($style) '
show_always = true

