# [plugins]
# preload = [
#   "~/.config/yazi/ui.lua"
# ]

[manager]
folder_offset = [2,0,2,0]
preview_offset = [2,1,2,1]
show_hidden = true
show_symlink = true
sort_by = 'natural'
sort_dir_first = true
sort_reverse = false
sort_sensitive = false

